# Generated by Django 3.0.5 on 2020-04-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='check_digit',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='check digit'),
        ),
    ]
