# Generated by Django 3.0.5 on 2020-04-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0004_auto_20200404_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='check_digit',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='check digit'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personal_email',
            field=models.EmailField(blank=True, default='', max_length=80, verbose_name='personal email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personal_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='personal phone'),
        ),
    ]
