# Generated by Django 3.0.5 on 2020-05-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0005_auto_20200404_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, default='', max_length=1000, null=True, upload_to='upload/%Y/%m/orig', verbose_name='logo'),
        ),
    ]
