# Generated by Django 3.0.5 on 2020-05-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0006_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='code'),
        ),
    ]
