# Generated by Django 3.0.5 on 2020-09-17 23:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0007_organization_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=100, verbose_name='commune')),
            ],
            options={
                'verbose_name_plural': 'communes',
            },
        ),
        migrations.CreateModel(
            name='TerritorialOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.CharField(max_length=50, unique=True, verbose_name='version code')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name_plural': 'territorial organizations',
            },
        ),
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, default='', max_length=250, verbose_name='name')),
                ('contact', models.TextField(blank=True, default='', verbose_name='contact')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/%Y/%m/orig', verbose_name='image')),
                ('address', models.CharField(blank=True, default='', max_length=250, verbose_name='address')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=12, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=12, null=True, verbose_name='longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.Commune', verbose_name='commune')),
                ('parent_subsidiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.Subsidiary', verbose_name='parent subsidiary')),
            ],
            options={
                'verbose_name': 'subsidiary',
                'verbose_name_plural': 'subsidiaries',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='region')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('capital', models.CharField(max_length=100, verbose_name='capital')),
                ('territorial_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.TerritorialOrganization', verbose_name='territorial organization')),
            ],
            options={
                'verbose_name_plural': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100, verbose_name='province')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.Region', verbose_name='region')),
            ],
            options={
                'verbose_name_plural': 'provinces',
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.Province', verbose_name='province'),
        ),
    ]
