# Generated by Django 3.0.5 on 2020-09-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0008_auto_20200917_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidiary',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='longitude'),
        ),
    ]
