# Generated by Django 3.0.5 on 2020-10-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0009_auto_20200918_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='image'),
        ),
    ]
