# Generated by Django 3.0.5 on 2020-10-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0010_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FilePathField(blank=True, default=None, null=True, verbose_name='image'),
        ),
    ]
