# Generated by Django 3.0.5 on 2020-10-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0011_auto_20201028_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FilePathField(blank=True, null=True, verbose_name='image'),
        ),
    ]
