# Generated by Django 3.0.5 on 2020-10-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0013_auto_20201028_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
