# Generated by Django 3.0.5 on 2020-10-28 04:24

from django.db import migrations, models
import logics.utils


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0014_auto_20201028_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=logics.utils.upload_file_sign, verbose_name='image'),
        ),
    ]
