# Generated by Django 3.0.5 on 2020-10-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0015_auto_20201028_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, default='', max_length=1000, null=True, upload_to='upload/%Y/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/%Y/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/temp/', verbose_name='image'),
        ),
    ]
