# Generated by Django 3.0.5 on 2021-01-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('app_general', '0016_auto_20201028_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldsPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('group_edit', models.ManyToManyField(blank=True, related_name='group_edit', to='auth.Group')),
                ('group_view', models.ManyToManyField(blank=True, related_name='group_view', to='auth.Group')),
            ],
            options={
                'verbose_name': 'fields permission',
                'verbose_name_plural': 'field permissions',
            },
        ),
    ]
