# Generated by Django 3.0.5 on 2021-01-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0017_fieldspermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('module', models.CharField(blank=True, choices=[('app_transport_services.contract', 'app_transport_services.contract'), ('app_transport_services.costcenter', 'app_transport_services.costcenter'), ('app_transport_services.driver', 'app_transport_services.driver'), ('app_transport_services.equipment', 'app_transport_services.equipment'), ('app_transport_services.equipmenttype', 'app_transport_services.equipmenttype'), ('app_transport_services.serviceorder', 'app_transport_services.serviceorder'), ('app_transport_services.worklogtype', 'app_transport_services.worklogtype'), ('app_transport_services.worklog', 'app_transport_services.worklog'), ('app_transport_services.driverserviceorder', 'app_transport_services.driverserviceorder'), ('app_transport_services.equipmentserviceorder', 'app_transport_services.equipmentserviceorder'), ('app_general.organization', 'app_general.organization'), ('app_general.userprofile', 'app_general.userprofile'), ('app_application.actiontype', 'app_application.actiontype'), ('app_application.application', 'app_application.application'), ('app_application.list', 'app_application.list'), ('app_application.listgrouppermission', 'app_application.listgrouppermission'), ('app_transport_services.servicecharge', 'app_transport_services.servicecharge'), ('app_transport_services.servicechargetype', 'app_transport_services.servicechargetype'), ('app_general.subsidiary', 'app_general.subsidiary'), ('app_general.region', 'app_general.region'), ('app_general.province', 'app_general.province'), ('app_general.commune', 'app_general.commune'), ('app_general.territorialorganization', 'app_general.territorialorganization'), ('app_transport_services.brand', 'app_transport_services.brand'), ('app_transport_services.serviceordertype', 'app_transport_services.serviceordertype'), ('app_transport_services.model', 'app_transport_services.model'), ('app_transport_services.servicecost', 'app_transport_services.servicecost'), ('app_transport_services.costtype', 'app_transport_services.costtype'), ('app_component.type', 'app_component.type'), ('app_component.location', 'app_component.location'), ('app_component.component', 'app_component.component'), ('app_component.attachedfiles', 'app_component.attachedfiles'), ('app_general.fieldspermission', 'app_general.fieldspermission'), ('app_component.workflow', 'app_component.workflow')], max_length=100, verbose_name='module')),
                ('code', models.CharField(blank=True, default='', max_length=100, verbose_name='code')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'precess',
                'verbose_name_plural': 'processes',
                'unique_together': {('code', 'module')},
            },
        ),
    ]
