# Generated by Django 3.0.5 on 2021-01-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0018_process'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name': 'process', 'verbose_name_plural': 'processes'},
        ),
        migrations.AlterField(
            model_name='process',
            name='module',
            field=models.CharField(blank=True, choices=[('app_transport_services.contract', 'app_transport_services.contract'), ('app_transport_services.costcenter', 'app_transport_services.costcenter'), ('app_transport_services.driver', 'app_transport_services.driver'), ('app_transport_services.equipment', 'app_transport_services.equipment'), ('app_transport_services.equipmenttype', 'app_transport_services.equipmenttype'), ('app_transport_services.serviceorder', 'app_transport_services.serviceorder'), ('app_transport_services.worklogtype', 'app_transport_services.worklogtype'), ('app_transport_services.worklog', 'app_transport_services.worklog'), ('app_transport_services.driverserviceorder', 'app_transport_services.driverserviceorder'), ('app_transport_services.equipmentserviceorder', 'app_transport_services.equipmentserviceorder'), ('app_general.organization', 'app_general.organization'), ('app_general.userprofile', 'app_general.userprofile'), ('app_application.actiontype', 'app_application.actiontype'), ('app_application.application', 'app_application.application'), ('app_application.list', 'app_application.list'), ('app_application.listgrouppermission', 'app_application.listgrouppermission'), ('app_transport_services.servicecharge', 'app_transport_services.servicecharge'), ('app_transport_services.servicechargetype', 'app_transport_services.servicechargetype'), ('app_general.subsidiary', 'app_general.subsidiary'), ('app_general.region', 'app_general.region'), ('app_general.province', 'app_general.province'), ('app_general.commune', 'app_general.commune'), ('app_general.territorialorganization', 'app_general.territorialorganization'), ('app_transport_services.brand', 'app_transport_services.brand'), ('app_transport_services.serviceordertype', 'app_transport_services.serviceordertype'), ('app_transport_services.model', 'app_transport_services.model'), ('app_transport_services.servicecost', 'app_transport_services.servicecost'), ('app_transport_services.costtype', 'app_transport_services.costtype'), ('app_component.type', 'app_component.type'), ('app_component.location', 'app_component.location'), ('app_component.component', 'app_component.component'), ('app_component.attachedfiles', 'app_component.attachedfiles'), ('app_general.fieldspermission', 'app_general.fieldspermission'), ('app_component.workflow', 'app_component.workflow'), ('app_general.process', 'app_general.process')], max_length=100, verbose_name='module'),
        ),
    ]
