# Generated by Django 3.0.5 on 2021-01-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0020_auto_20210118_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='process',
            name='module',
            field=models.CharField(blank=True, choices=[('app_application.actiontype', 'app_application.actiontype'), ('app_application.aplicación', 'app_application.aplicación'), ('app_application.list', 'app_application.list'), ('app_application.listgrouppermission', 'app_application.listgrouppermission'), ('app_component.attachedfiles', 'app_component.attachedfiles'), ('app_component.workflow', 'app_component.workflow'), ('app_component.tipo', 'app_component.tipo'), ('app_component.ubicación', 'app_component.ubicación'), ('app_component.inventario', 'app_component.inventario'), ('app_general.userprofile', 'app_general.userprofile'), ('app_general.region', 'app_general.region'), ('app_general.provincia', 'app_general.provincia'), ('app_general.comuna', 'app_general.comuna'), ('app_general.territorialorganization', 'app_general.territorialorganization'), ('app_general.organización', 'app_general.organización'), ('app_general.fieldspermission', 'app_general.fieldspermission'), ('app_general.process', 'app_general.process'), ('app_general.sucursal', 'app_general.sucursal'), ('app_transport_services.servicechargetype', 'app_transport_services.servicechargetype'), ('app_transport_services.costcenter', 'app_transport_services.costcenter'), ('app_transport_services.conductor', 'app_transport_services.conductor'), ('app_transport_services.equipo', 'app_transport_services.equipo'), ('app_transport_services.equipmenttype', 'app_transport_services.equipmenttype'), ('app_transport_services.serviceorder', 'app_transport_services.serviceorder'), ('app_transport_services.worklogtype', 'app_transport_services.worklogtype'), ('app_transport_services.worklog', 'app_transport_services.worklog'), ('app_transport_services.driverserviceorder', 'app_transport_services.driverserviceorder'), ('app_transport_services.equipmentserviceorder', 'app_transport_services.equipmentserviceorder'), ('app_transport_services.servicecharge', 'app_transport_services.servicecharge'), ('app_transport_services.contrato', 'app_transport_services.contrato'), ('app_transport_services.marca', 'app_transport_services.marca'), ('app_transport_services.serviceordertype', 'app_transport_services.serviceordertype'), ('app_transport_services.modelo', 'app_transport_services.modelo'), ('app_transport_services.servicecost', 'app_transport_services.servicecost'), ('app_transport_services.costtype', 'app_transport_services.costtype')], max_length=100, verbose_name='module'),
        ),
    ]
