# Generated by Django 3.0.5 on 2021-01-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0022_auto_20210118_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
    ]
