# Generated by Django 3.0.5 on 2021-01-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0023_auto_20210118_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='order',
            field=models.IntegerField(default=0, null=True, verbose_name='order'),
        ),
    ]
