# Generated by Django 3.0.5 on 2021-01-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0024_process_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='workflow_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='workflow name'),
        ),
    ]
