# Generated by Django 3.0.5 on 2021-01-19 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0025_process_workflow_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='workflow_name',
            field=models.CharField(blank=True, default='workflow', max_length=100, verbose_name='workflow name'),
        ),
        migrations.CreateModel(
            name='FieldName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('value', models.CharField(blank=True, default='', max_length=150, verbose_name='value')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_general.Process', verbose_name='process')),
            ],
            options={
                'verbose_name': 'fields name',
                'verbose_name_plural': 'field names',
                'unique_together': {('process',)},
            },
        ),
    ]
