# Generated by Django 3.0.5 on 2021-01-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0027_auto_20210119_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldname',
            name='fieldLabel',
        ),
    ]
