# Generated by Django 3.0.5 on 2021-01-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0028_remove_fieldname_fieldlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldname',
            name='key',
            field=models.CharField(default='', max_length=250, unique=True, verbose_name='key'),
        ),
        migrations.AlterUniqueTogether(
            name='fieldname',
            unique_together={('process', 'key')},
        ),
    ]
