# Generated by Django 3.0.5 on 2021-01-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0029_auto_20210119_1218'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fieldname',
            unique_together=set(),
        ),
    ]
