# Generated by Django 3.0.5 on 2021-01-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0030_auto_20210119_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldname',
            name='key',
            field=models.CharField(default='', max_length=250, verbose_name='key'),
        ),
        migrations.AlterUniqueTogether(
            name='fieldname',
            unique_together={('process', 'key')},
        ),
    ]
