# Generated by Django 3.0.5 on 2021-01-20 04:27

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0031_auto_20210119_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldname',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('number', 'Positive Number'), ('select', 'Select'), ('textarea', 'Textarea')], default='text', max_length=250, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='process',
            name='color',
            field=colorfield.fields.ColorField(default='#EEEEEE', max_length=18, verbose_name='color'),
        ),
    ]
