# Generated by Django 3.0.5 on 2021-01-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0032_auto_20210120_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldname',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('number+', 'Positive Number'), ('select', 'Select'), ('textarea', 'Textarea')], default='text', max_length=250, verbose_name='type'),
        ),
    ]
