# Generated by Django 3.0.5 on 2021-01-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0033_auto_20210120_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldname',
            name='default_value',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='default_value'),
        ),
    ]
