# Generated by Django 3.0.5 on 2021-01-21 09:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0035_auto_20210120_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldname',
            name='conditions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='conditions'),
        ),
        migrations.AddField(
            model_name='fieldname',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='is visible'),
        ),
    ]
