# Generated by Django 3.0.5 on 2021-01-21 09:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0039_auto_20210121_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldname',
            name='conditions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='conditions'),
        ),
    ]
