# Generated by Django 3.0.5 on 2021-01-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0041_auto_20210121_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='module',
            field=models.CharField(blank=True, choices=[('app_application.actiontype', 'app_application.actiontype'), ('app_application.listgrouppermission', 'app_application.listgrouppermission'), ('app_application.list', 'app_application.list'), ('app_application.application', 'app_application.aplicación'), ('app_component.workflowlog', 'app_component.workflowlog'), ('app_component.type', 'app_component.tipo'), ('app_component.location', 'app_component.ubicación'), ('app_component.workflow', 'app_component.workflow'), ('app_component.attachedfiles', 'app_component.attachedfiles'), ('app_component.component', 'app_component.inventario'), ('app_general.subsidiary', 'app_general.sucursal'), ('app_general.organization', 'app_general.organización'), ('app_general.userprofile', 'app_general.userprofile'), ('app_general.region', 'app_general.region'), ('app_general.province', 'app_general.provincia'), ('app_general.commune', 'app_general.comuna'), ('app_general.territorialorganization', 'app_general.territorialorganization'), ('app_general.fieldspermission', 'app_general.fieldspermission'), ('app_general.process', 'app_general.process'), ('app_general.fieldname', 'app_general.fieldname'), ('app_transport_services.equipment', 'app_transport_services.equipo'), ('app_transport_services.costcenter', 'app_transport_services.costcenter'), ('app_transport_services.driver', 'app_transport_services.conductor'), ('app_transport_services.brand', 'app_transport_services.marca'), ('app_transport_services.serviceordertype', 'app_transport_services.serviceordertype'), ('app_transport_services.model', 'app_transport_services.modelo'), ('app_transport_services.servicecost', 'app_transport_services.servicecost'), ('app_transport_services.costtype', 'app_transport_services.costtype'), ('app_transport_services.worklogtype', 'app_transport_services.worklogtype'), ('app_transport_services.serviceorder', 'app_transport_services.serviceorder'), ('app_transport_services.equipmentserviceorder', 'app_transport_services.equipmentserviceorder'), ('app_transport_services.driverserviceorder', 'app_transport_services.driverserviceorder'), ('app_transport_services.worklog', 'app_transport_services.worklog'), ('app_transport_services.servicecharge', 'app_transport_services.servicecharge'), ('app_transport_services.servicechargetype', 'app_transport_services.servicechargetype'), ('app_transport_services.contract', 'app_transport_services.contrato'), ('app_transport_services.equipmenttype', 'app_transport_services.equipmenttype')], max_length=100, verbose_name='module'),
        ),
    ]
