# Generated by Django 3.0.5 on 2021-02-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0042_auto_20210125_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='subsidiaries',
            field=models.ManyToManyField(blank=True, to='app_general.Subsidiary', verbose_name='subsidiaries'),
        ),
    ]
