# Generated by Django 3.0.5 on 2021-02-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('app_general', '0043_process_subsidiaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editors', to='auth.Group', verbose_name='editors'),
        ),
        migrations.AddField(
            model_name='process',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewers', to='auth.Group', verbose_name='viewers'),
        ),
    ]
