# Generated by Django 3.0.5 on 2021-02-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0044_auto_20210209_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('quantity', models.CharField(blank=True, choices=[('app_application.actiontype', 'app_application.actiontype'), ('app_application.listgrouppermission', 'app_application.listgrouppermission'), ('app_application.list', 'app_application.list'), ('app_application.application', 'app_application.aplicación'), ('app_component.workflowlog', 'app_component.workflowlog'), ('app_component.type', 'app_component.tipo'), ('app_component.location', 'app_component.ubicación'), ('app_component.workflow', 'app_component.workflow'), ('app_component.attachedfiles', 'app_component.attachedfiles'), ('app_component.component', 'app_component.inventario'), ('app_general.subsidiary', 'app_general.sucursal'), ('app_general.organization', 'app_general.organización'), ('app_general.userprofile', 'app_general.userprofile'), ('app_general.region', 'app_general.region'), ('app_general.province', 'app_general.provincia'), ('app_general.commune', 'app_general.comuna'), ('app_general.territorialorganization', 'app_general.territorialorganization'), ('app_general.fieldspermission', 'app_general.fieldspermission'), ('app_general.process', 'app_general.process'), ('app_general.fieldname', 'app_general.fieldname'), ('app_transport_services.equipment', 'app_transport_services.equipo'), ('app_transport_services.costcenter', 'app_transport_services.costcenter'), ('app_transport_services.driver', 'app_transport_services.conductor'), ('app_transport_services.brand', 'app_transport_services.marca'), ('app_transport_services.serviceordertype', 'app_transport_services.serviceordertype'), ('app_transport_services.model', 'app_transport_services.modelo'), ('app_transport_services.servicecost', 'app_transport_services.servicecost'), ('app_transport_services.costtype', 'app_transport_services.costtype'), ('app_transport_services.worklogtype', 'app_transport_services.worklogtype'), ('app_transport_services.serviceorder', 'app_transport_services.serviceorder'), ('app_transport_services.equipmentserviceorder', 'app_transport_services.equipmentserviceorder'), ('app_transport_services.driverserviceorder', 'app_transport_services.driverserviceorder'), ('app_transport_services.worklog', 'app_transport_services.worklog'), ('app_transport_services.servicecharge', 'app_transport_services.servicecharge'), ('app_transport_services.servicechargetype', 'app_transport_services.servicechargetype'), ('app_transport_services.contract', 'app_transport_services.contrato'), ('app_transport_services.equipmenttype', 'app_transport_services.equipmenttype')], max_length=120, verbose_name='module')),
                ('create_data', models.DateTimeField(blank=True, default=None, null=True, verbose_name='create data')),
                ('version', models.CharField(blank=True, default='', max_length=120, verbose_name='version')),
                ('str_date', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='str date')),
                ('str_state', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='str state')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrdersItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, choices=[('app_application.actiontype', 'app_application.actiontype'), ('app_application.listgrouppermission', 'app_application.listgrouppermission'), ('app_application.list', 'app_application.list'), ('app_application.application', 'app_application.aplicación'), ('app_component.workflowlog', 'app_component.workflowlog'), ('app_component.type', 'app_component.tipo'), ('app_component.location', 'app_component.ubicación'), ('app_component.workflow', 'app_component.workflow'), ('app_component.attachedfiles', 'app_component.attachedfiles'), ('app_component.component', 'app_component.inventario'), ('app_general.subsidiary', 'app_general.sucursal'), ('app_general.organization', 'app_general.organización'), ('app_general.userprofile', 'app_general.userprofile'), ('app_general.region', 'app_general.region'), ('app_general.province', 'app_general.provincia'), ('app_general.commune', 'app_general.comuna'), ('app_general.territorialorganization', 'app_general.territorialorganization'), ('app_general.fieldspermission', 'app_general.fieldspermission'), ('app_general.process', 'app_general.process'), ('app_general.fieldname', 'app_general.fieldname'), ('app_transport_services.equipment', 'app_transport_services.equipo'), ('app_transport_services.costcenter', 'app_transport_services.costcenter'), ('app_transport_services.driver', 'app_transport_services.conductor'), ('app_transport_services.brand', 'app_transport_services.marca'), ('app_transport_services.serviceordertype', 'app_transport_services.serviceordertype'), ('app_transport_services.model', 'app_transport_services.modelo'), ('app_transport_services.servicecost', 'app_transport_services.servicecost'), ('app_transport_services.costtype', 'app_transport_services.costtype'), ('app_transport_services.worklogtype', 'app_transport_services.worklogtype'), ('app_transport_services.serviceorder', 'app_transport_services.serviceorder'), ('app_transport_services.equipmentserviceorder', 'app_transport_services.equipmentserviceorder'), ('app_transport_services.driverserviceorder', 'app_transport_services.driverserviceorder'), ('app_transport_services.worklog', 'app_transport_services.worklog'), ('app_transport_services.servicecharge', 'app_transport_services.servicecharge'), ('app_transport_services.servicechargetype', 'app_transport_services.servicechargetype'), ('app_transport_services.contract', 'app_transport_services.contrato'), ('app_transport_services.equipmenttype', 'app_transport_services.equipmenttype')], max_length=120, verbose_name='code')),
                ('name', models.CharField(blank=True, default='workflow', max_length=250, verbose_name='name')),
                ('code_state', models.CharField(blank=True, default='', max_length=120, verbose_name='code state')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
    ]
