# Generated by Django 3.0.5 on 2021-02-11 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0046_auto_20210211_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.Orders', verbose_name='order'),
        ),
    ]
