# Generated by Django 3.0.5 on 2021-02-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0047_ordersitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='quantity'),
        ),
    ]
