# Generated by Django 3.0.5 on 2021-02-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0048_auto_20210211_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersitem',
            name='name',
            field=models.TextField(blank=True, default='workflow', max_length=250, verbose_name='name'),
        ),
    ]
