# Generated by Django 3.0.5 on 2021-02-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0049_auto_20210211_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='create_data',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='create data'),
        ),
    ]
