# Generated by Django 3.0.5 on 2021-02-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0050_auto_20210211_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersitem',
            name='code',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='code'),
        ),
    ]
