# Generated by Django 3.0.5 on 2021-02-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0052_auto_20210225_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload/%Y/', verbose_name='logo'),
        ),
    ]
