# Generated by Django 3.0.5 on 2021-03-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0054_auto_20210227_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/%Y/%m/orig', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/orig', verbose_name='image'),
        ),
    ]
