# Generated by Django 3.0.5 on 2021-03-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0056_auto_20210309_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldname',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('number+', 'Positive Number'), ('select', 'Select'), ('textarea', 'Textarea'), ('check', 'Check'), ('upload', 'Upload'), ('conditional', 'Conditional')], default='text', max_length=250, verbose_name='type'),
        ),
    ]
