# Generated by Django 3.0.5 on 2021-03-14 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_general', '0058_auto_20210314_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=100, verbose_name='key')),
                ('code', models.CharField(max_length=100, verbose_name='code')),
                ('value', models.TextField(blank=True, null=True, verbose_name='value')),
                ('context_type', models.IntegerField(verbose_name='context_type')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('editor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='editor user')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_general.Process', verbose_name='process')),
            ],
            options={
                'verbose_name': 'workflow value',
                'verbose_name_plural': 'workflow values',
                'unique_together': {('process', 'key', 'is_removed')},
            },
        ),
    ]
