# Generated by Django 3.0.5 on 2021-03-14 06:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0060_auto_20210314_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldname',
            name='column_attr',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default="{'size-xs': '12', 'size-md': '6', 'size-lg': '6'}", null=True, verbose_name='column attributes'),
        ),
        migrations.AddField(
            model_name='fieldname',
            name='order',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='order'),
        ),
    ]
