# Generated by Django 3.0.5 on 2021-03-14 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0064_fieldname_column_attr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldname',
            name='column_attr',
        ),
    ]
