# Generated by Django 3.0.5 on 2021-03-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0068_fieldname_column_attr'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldname',
            name='icon',
            field=models.CharField(default='', max_length=60, verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='process',
            name='icon',
            field=models.CharField(default='', max_length=60, verbose_name='icon'),
        ),
    ]
