# Generated by Django 3.0.5 on 2021-03-14 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0073_fieldname_column_attr'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.Organization', verbose_name='organization'),
        ),
    ]
