# Generated by Django 3.0.5 on 2021-03-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0074_process_organization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='process',
            unique_together={('code', 'module', 'organization')},
        ),
    ]
