# Generated by Django 3.0.5 on 2021-03-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0075_auto_20210314_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldname',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='process',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='icon'),
        ),
    ]
