# Generated by Django 3.0.5 on 2021-03-14 21:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0076_auto_20210314_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldname',
            name='filter',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='filter'),
        ),
    ]
