# Generated by Django 3.0.5 on 2021-03-14 22:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0077_fieldname_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldname',
            name='exclude',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='exclude'),
        ),
    ]
