# Generated by Django 3.0.5 on 2021-03-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0078_fieldname_exclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldname',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('number+', 'Positive Number'), ('select', 'Select'), ('textarea', 'Textarea'), ('check', 'Check'), ('upload', 'Upload'), ('multiselect', 'Multiselect'), ('scanner', 'Scanner'), ('conditional', 'Conditional')], default='text', max_length=250, verbose_name='type'),
        ),
    ]
