# Generated by Django 3.0.5 on 2021-03-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0080_auto_20210315_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldname',
            name='api_get',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='api get'),
        ),
        migrations.AlterField(
            model_name='fieldname',
            name='api_post',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='api post'),
        ),
        migrations.AlterField(
            model_name='fieldname',
            name='api_put',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='api put'),
        ),
    ]
