# Generated by Django 3.0.5 on 2021-03-15 07:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0081_auto_20210315_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldname',
            name='input_value',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='input value'),
        ),
    ]
