# Generated by Django 3.0.5 on 2021-03-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0082_fieldname_input_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldname',
            name='api_get',
        ),
        migrations.RemoveField(
            model_name='fieldname',
            name='api_post',
        ),
        migrations.RemoveField(
            model_name='fieldname',
            name='api_put',
        ),
        migrations.AddField(
            model_name='fieldname',
            name='api_context',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='api context'),
        ),
        migrations.AddField(
            model_name='fieldname',
            name='api_list',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='api list'),
        ),
    ]
