# Generated by Django 3.0.5 on 2021-03-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0083_auto_20210315_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldname',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='title'),
        ),
    ]
