# Generated by Django 3.0.5 on 2021-03-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0084_fieldname_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldname',
            name='title',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='title'),
        ),
    ]
