# Generated by Django 3.0.5 on 2021-03-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0086_auto_20210315_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldname',
            name='anchor_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='anchor field'),
        ),
    ]
