# Generated by Django 3.0.5 on 2021-07-30 06:04

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0095_auto_20210507_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, default='', max_length=250, verbose_name='name')),
                ('ni', models.IntegerField(blank=True, default=None, null=True, unique=True, verbose_name='identification number')),
                ('check_digit', models.CharField(blank=True, default='', max_length=1, verbose_name='check digit')),
                ('code', models.CharField(blank=True, default='', max_length=250, verbose_name='code')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='longitude')),
                ('website', models.URLField(blank=True, max_length=250, null=True, verbose_name='website')),
                ('color', colorfield.fields.ColorField(default='#EEEEEE', max_length=18, verbose_name='color')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='email')),
                ('contact_data', models.CharField(blank=True, default='', max_length=250, verbose_name='contact_data')),
                ('bank_account_data', models.TextField(blank=True, default='', verbose_name='bank account data')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/%Y/%m/orig', verbose_name='image')),
                ('stamp', models.URLField(blank=True, null=True, verbose_name='stamp')),
                ('address', models.TextField(blank=True, default='', verbose_name='address')),
                ('default_commission', models.IntegerField(default=0, verbose_name='default commission')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.Commune', verbose_name='commune')),
                ('parent_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_provider_rel', to='app_general.Provider', verbose_name='parent provider')),
            ],
            options={
                'verbose_name': 'provider',
                'verbose_name_plural': 'providers',
            },
        ),
    ]
