# Generated by Django 3.2.5 on 2021-07-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0097_auto_20210730_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldname',
            name='column_attr',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='column attributes'),
        ),
    ]
