# Generated by Django 3.2.5 on 2021-07-30 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0098_alter_fieldname_column_attr'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_rel', to='app_general.provider', verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='fieldname',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='conditions'),
        ),
        migrations.AlterField(
            model_name='fieldname',
            name='exclude',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='exclude'),
        ),
        migrations.AlterField(
            model_name='fieldname',
            name='filter',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='filter'),
        ),
        migrations.AlterField(
            model_name='fieldname',
            name='input_value',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='input value'),
        ),
    ]
