# Generated by Django 3.2.5 on 2021-08-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0100_userprofile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldname',
            name='item_adapter',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='item adapter'),
        ),
    ]
