# Generated by Django 3.2.5 on 2021-08-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0101_fieldname_item_adapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldname',
            name='item_adapter',
            field=models.TextField(blank=True, default=dict, null=True, verbose_name='item adapter'),
        ),
    ]
