# Generated by Django 3.2.5 on 2021-08-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0102_alter_fieldname_item_adapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldname',
            name='text_selected_item',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='text of selected item'),
        ),
        migrations.AlterField(
            model_name='fieldname',
            name='default_value',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='default value'),
        ),
    ]
