# Generated by Django 3.2.5 on 2021-08-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0104_alter_process_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldname',
            name='save_in_parent',
            field=models.BooleanField(default=False, null=True, verbose_name='save value in parent'),
        ),
    ]
