# Generated by Django 3.2.5 on 2021-09-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0106_alter_process_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldname',
            name='css_class',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='css_class'),
        ),
    ]
