# Generated by Django 3.2.5 on 2021-09-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0107_fieldname_css_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldname',
            name='css_class',
            field=models.TextField(blank=True, default='', max_length=250, verbose_name='css class'),
        ),
    ]
