# Generated by Django 3.0.5 on 2020-05-07 05:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('app_general', '0005_auto_20200404_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='code')),
            ],
            options={
                'verbose_name_plural': 'type of actions',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('code', models.CharField(blank=True, max_length=250, verbose_name='code')),
                ('domain', models.URLField(blank=True)),
                ('repository', models.CharField(blank=True, max_length=250, verbose_name='repository')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name='description')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_general.Organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('code', models.CharField(blank=True, max_length=256, null=True, verbose_name='code')),
                ('action_value', models.CharField(blank=True, max_length=256, null=True, verbose_name='action value')),
                ('custom_style', models.CharField(blank=True, max_length=100, null=True, verbose_name='custom style')),
                ('file', models.FileField(default='', max_length=1000, upload_to='upload/%Y/%m/orig', verbose_name='file')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('action_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_application.ActionType', verbose_name='action type')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_application.Application', verbose_name='application')),
                ('parent_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_application.List', verbose_name='parent list')),
            ],
            options={
                'verbose_name_plural': 'lists',
            },
        ),
        migrations.CreateModel(
            name='ListGroupPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='group')),
                ('lists', models.ManyToManyField(to='app_application.List', verbose_name='lists')),
            ],
            options={
                'verbose_name_plural': 'list group permissions',
            },
        ),
    ]
