# Generated by Django 3.0.5 on 2020-05-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
