# Generated by Django 3.0.5 on 2020-05-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0002_application_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='file',
            field=models.FileField(blank=True, default='', max_length=1000, null=True, upload_to='upload/%Y/%m/orig', verbose_name='file'),
        ),
    ]
