# Generated by Django 3.0.5 on 2020-05-07 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0003_auto_20200507_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='parent_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_application.List', verbose_name='parent list'),
        ),
    ]
