# Generated by Django 3.0.5 on 2020-05-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0004_auto_20200507_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontype',
            name='description',
            field=models.TextField(blank=True, max_length=250, verbose_name='description'),
        ),
    ]
