# Generated by Django 3.0.5 on 2020-05-08 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0005_actiontype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='action_type',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='app_application.ActionType', verbose_name='action type'),
        ),
        migrations.AlterField(
            model_name='list',
            name='action_value',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='action value'),
        ),
        migrations.AlterField(
            model_name='list',
            name='code',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='list',
            name='custom_style',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='custom style'),
        ),
        migrations.AlterField(
            model_name='list',
            name='file',
            field=models.FileField(blank=True, default='', max_length=1000, upload_to='upload/%Y/%m/orig', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='list',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(default='', max_length=256, verbose_name='title'),
        ),
    ]
