# Generated by Django 3.0.5 on 2020-10-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0006_auto_20200508_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='file',
            field=models.FileField(blank=True, default='', max_length=1000, upload_to='upload/%Y/', verbose_name='file'),
        ),
    ]
