# Generated by Django 3.0.5 on 2021-03-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0007_auto_20201028_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='file',
            field=models.FileField(blank=True, default='', max_length=1000, upload_to='images/%Y/%m/orig', verbose_name='file'),
        ),
    ]
