# Generated by Django 3.0.5 on 2021-04-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0008_auto_20210302_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images/%Y/%m/orig', verbose_name='file'),
        ),
    ]
