# Generated by Django 3.0.5 on 2021-02-27 07:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_general', '0053_auto_20210227_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('alt', models.CharField(max_length=255, verbose_name='alt')),
                ('code', models.CharField(max_length=100, verbose_name='code')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/%Y/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/%Y/', verbose_name='image')),
                ('state', models.CharField(choices=[('publish', 'publish'), ('pending', 'pending'), ('private', 'private'), ('draft', 'draft')], default='publish', max_length=255, verbose_name='state')),
                ('length', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=12, null=True, verbose_name='length')),
                ('width', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=12, null=True, verbose_name='width')),
                ('height', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=12, null=True, verbose_name='height')),
                ('short_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='short description')),
                ('price_1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='price 1')),
                ('price_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='price 2')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=12, null=True, verbose_name='weight')),
                ('manage_stock', models.BooleanField(default=True, verbose_name='manage stock')),
                ('stock_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='stock quantity')),
                ('stock_status', models.CharField(choices=[('instock', 'instock'), ('outofstock', 'outofstock'), ('onbackorder', 'onbackorder')], max_length=255, verbose_name='stock status')),
                ('virtual', models.BooleanField(default=True, verbose_name='virtual')),
                ('images', models.ManyToManyField(blank=True, to='app_catalog.Images', verbose_name='images')),
                ('organization', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.Organization', verbose_name='organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_catalog.Product', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='key')),
                ('code', models.CharField(max_length=100, verbose_name='code')),
                ('value', models.TextField(blank=True, null=True, verbose_name='value')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_catalog.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'meta data',
                'verbose_name_plural': 'meta data',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/%Y/', verbose_name='image')),
                ('state', models.CharField(choices=[('publish', 'publish'), ('pending', 'pending'), ('private', 'private'), ('draft', 'draft')], default='publish', max_length=255, verbose_name='state')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='order')),
                ('images', models.ManyToManyField(blank=True, to='app_catalog.Images', verbose_name='images')),
                ('organization', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.Organization', verbose_name='organization')),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_catalog.Category', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/%Y/', verbose_name='image')),
                ('state', models.CharField(choices=[('publish', 'publish'), ('pending', 'pending'), ('private', 'private'), ('draft', 'draft')], default='publish', max_length=255, verbose_name='state')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='order')),
                ('images', models.ManyToManyField(blank=True, to='app_catalog.Images', verbose_name='images')),
                ('organization', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.Organization', verbose_name='organization')),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_catalog.Brand', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
    ]
