# Generated by Django 3.0.5 on 2021-02-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='images',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt'),
        ),
        migrations.AlterField(
            model_name='images',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='upload/%Y/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manage_stock',
            field=models.BooleanField(default=False, verbose_name='manage stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='price 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='price 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='stock quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='virtual',
            field=models.BooleanField(default=False, verbose_name='virtual'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='weight'),
        ),
    ]
