# Generated by Django 3.0.5 on 2021-03-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0002_auto_20210227_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='style',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='style'),
        ),
        migrations.AddField(
            model_name='category',
            name='style',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='style'),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='style'),
        ),
    ]
