# Generated by Django 3.0.5 on 2021-03-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0008_auto_20210302_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='app_catalog.Category', verbose_name='categories'),
        ),
    ]
