# Generated by Django 3.0.5 on 2021-03-29 18:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0089_auto_20210321_1936'),
        ('app_catalog', '0009_auto_20210303_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('file', models.FileField(default='', max_length=500, upload_to='images/%Y/%m/orig', verbose_name='file')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('uploaded', models.BooleanField(default=False, verbose_name='uploaded')),
                ('organization', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.Organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'import file',
                'verbose_name_plural': 'import files',
            },
        ),
    ]
