# Generated by Django 3.0.5 on 2021-03-30 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0010_importfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='images_zip',
            field=models.FileField(default='', upload_to='images/%Y/%m/orig', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='images zip'),
        ),
    ]
