# Generated by Django 3.0.5 on 2021-03-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0011_importfile_images_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, choices=[('CLP', 'Peso Chileno (CLP)'), ('PEN', 'Sol (PEN)')], max_length=255, null=True, verbose_name='currency'),
        ),
    ]
