# Generated by Django 3.0.5 on 2021-03-30 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_catalog', '0013_importfile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user created'),
        ),
    ]
