# Generated by Django 3.0.5 on 2021-03-30 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0014_importfile_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='file',
            field=models.FileField(default='', upload_to='images/%Y/%m/orig', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='images_zip',
            field=models.FileField(blank=True, null=True, upload_to='images/%Y/%m/orig', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='images zip'),
        ),
    ]
