# Generated by Django 3.0.5 on 2021-03-30 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0090_auto_20210330_0826'),
        ('app_catalog', '0015_auto_20210330_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.Organization', verbose_name='organization'),
        ),
    ]
