# Generated by Django 3.0.5 on 2021-03-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0016_images_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='virtual',
            field=models.BooleanField(default=False, verbose_name='virtual'),
        ),
        migrations.AddField(
            model_name='category',
            name='virtual',
            field=models.BooleanField(default=False, verbose_name='virtual'),
        ),
    ]
