# Generated by Django 3.0.5 on 2021-04-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0090_auto_20210330_0826'),
        ('app_catalog', '0017_auto_20210330_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/orig', verbose_name='image')),
                ('style', models.CharField(blank=True, default='', max_length=255, verbose_name='style')),
                ('state', models.CharField(choices=[('publish', 'publish'), ('pending', 'pending'), ('private', 'private'), ('draft', 'draft')], default='publish', max_length=255, verbose_name='state')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='order')),
                ('virtual', models.BooleanField(default=False, verbose_name='virtual')),
                ('images', models.ManyToManyField(blank=True, to='app_catalog.Images', verbose_name='images')),
                ('organization', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.Organization', verbose_name='organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_catalog.Slide', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'slide',
                'verbose_name_plural': 'slides',
            },
        ),
    ]
