# Generated by Django 3.0.5 on 2021-04-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0018_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/orig', verbose_name='icon file'),
        ),
    ]
