# Generated by Django 3.0.5 on 2021-05-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0019_category_icon_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='remove_all',
            field=models.BooleanField(default=False, verbose_name='remove all'),
        ),
    ]
