# Generated by Django 3.0.5 on 2020-04-03 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=80, verbose_name='code')),
            ],
            options={
                'verbose_name': 'contract',
                'verbose_name_plural': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, default='', max_length=120, verbose_name='name')),
                ('address', models.CharField(blank=True, default='', max_length=250, verbose_name='address')),
                ('contact', models.CharField(blank=True, default='', max_length=120, verbose_name='contact')),
            ],
            options={
                'verbose_name': 'cost center',
                'verbose_name_plural': 'centers of costs',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('license_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='license date')),
                ('contracts', models.ManyToManyField(blank=True, to='app_transport_services.Contract', verbose_name='contract')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'driver',
                'verbose_name_plural': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('patent', models.CharField(blank=True, max_length=80, null=True, verbose_name='patent')),
                ('circulation_permit_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='circulation permit date')),
                ('contracts', models.ManyToManyField(blank=True, to='app_transport_services.Contract', verbose_name='contract')),
            ],
            options={
                'verbose_name': 'equipment',
                'verbose_name_plural': 'equipments',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='name')),
            ],
            options={
                'verbose_name': 'equipment type',
                'verbose_name_plural': 'type of equipments',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('service_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='service date')),
                ('address', models.CharField(blank=True, default='', max_length=250, verbose_name='address')),
                ('office_guide', models.CharField(blank=True, default='', max_length=250, verbose_name='office guide')),
                ('amount', models.BigIntegerField(blank=True, default=0, verbose_name='amount')),
                ('estimated_closing_date', models.DateTimeField(default=None, verbose_name='estimated closing date')),
                ('priority', models.BooleanField(blank=True, default=False, verbose_name='priority')),
                ('cost_center', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.CostCenter', verbose_name='cost center')),
                ('drivers', models.ManyToManyField(blank=True, to='app_transport_services.Driver', verbose_name='driver')),
                ('equipments', models.ManyToManyField(blank=True, to='app_transport_services.Equipment', verbose_name='equipments')),
            ],
            options={
                'verbose_name': 'service order',
                'verbose_name_plural': 'order of services',
            },
        ),
        migrations.CreateModel(
            name='WorkLogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, default='', max_length=120, verbose_name='name')),
                ('value', models.CharField(blank=True, default='', max_length=120, verbose_name='value')),
            ],
            options={
                'verbose_name': 'work log type',
                'verbose_name_plural': 'work logs types',
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('service_order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.ServiceOrder', verbose_name='service order')),
                ('type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.WorkLogType', verbose_name='type')),
            ],
            options={
                'verbose_name': 'work log',
                'verbose_name_plural': 'work logs',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.EquipmentType', verbose_name='equipment type'),
        ),
    ]
