# Generated by Django 3.0.5 on 2020-04-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklogtype',
            name='value',
        ),
        migrations.AddField(
            model_name='worklog',
            name='value',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='value'),
        ),
    ]
