# Generated by Django 3.0.5 on 2020-04-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0002_auto_20200403_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='license date'),
        ),
    ]
