# Generated by Django 3.0.5 on 2020-04-04 12:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0003_auto_20200403_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='drivers',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='equipments',
        ),
        migrations.CreateModel(
            name='EquipmentServiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('1', 'first'), ('2', 'second'), ('3', 'third'), ('4', 'fourth'), ('5', 'fifth'), ('6', 'sixth'), ('7', 'seventh')], default=1, max_length=255, verbose_name='equipment type')),
                ('equipment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.Equipment', verbose_name='equipment')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.ServiceOrder', verbose_name='service order')),
            ],
            options={
                'verbose_name': 'equipment by service order',
                'verbose_name_plural': 'equipment by order of services',
            },
        ),
        migrations.CreateModel(
            name='DriverServiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('1', 'first'), ('2', 'second'), ('3', 'third'), ('4', 'fourth'), ('5', 'fifth'), ('6', 'sixth'), ('7', 'seventh')], default=1, max_length=255, verbose_name='driver type')),
                ('driver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.Driver', verbose_name='driver')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.ServiceOrder', verbose_name='service order')),
            ],
            options={
                'verbose_name': 'driver by service order',
                'verbose_name_plural': 'driver by order of services',
            },
        ),
    ]
