# Generated by Django 3.0.5 on 2020-04-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0004_auto_20200404_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverserviceorder',
            name='type',
            field=models.CharField(choices=[('1', 'first'), ('2', 'second'), ('3', 'third'), ('4', 'fourth'), ('5', 'fifth'), ('6', 'sixth'), ('7', 'seventh')], default=1, max_length=255, verbose_name='type place'),
        ),
        migrations.AlterField(
            model_name='equipmentserviceorder',
            name='type',
            field=models.CharField(choices=[('1', 'first'), ('2', 'second'), ('3', 'third'), ('4', 'fourth'), ('5', 'fifth'), ('6', 'sixth'), ('7', 'seventh')], default=1, max_length=255, verbose_name='type place'),
        ),
    ]
