# Generated by Django 3.0.5 on 2020-04-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0001_initial'),
        ('app_transport_services', '0006_auto_20200404_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.AddField(
            model_name='driver',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.UserProfile', verbose_name='user profile'),
        ),
    ]
