# Generated by Django 3.0.5 on 2020-04-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0007_auto_20200404_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='circulation_permit_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='circulation permit date'),
        ),
    ]
