# Generated by Django 3.0.5 on 2020-04-05 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0008_auto_20200404_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='contract',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.Contract', verbose_name='contract'),
        ),
    ]
