# Generated by Django 3.0.5 on 2020-04-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0009_serviceorder_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
    ]
