# Generated by Django 3.0.5 on 2020-04-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0010_worklog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='estimated_closing_time',
            field=models.TimeField(blank=True, default='00:00:00', null=True, verbose_name='estimated closing time'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='service_time',
            field=models.TimeField(blank=True, default='00:00:00', null=True, verbose_name='service time'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='estimated_closing_date',
            field=models.DateField(default=None, verbose_name='estimated closing date'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='service_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='service date'),
        ),
    ]
