# Generated by Django 3.0.5 on 2020-04-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0011_auto_20200417_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='service_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='service date'),
        ),
    ]
