# Generated by Django 3.0.5 on 2020-04-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0012_auto_20200417_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='estimated_closing_time',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='service_time',
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='estimated_closing_date',
            field=models.DateTimeField(default=None, verbose_name='estimated closing date'),
        ),
    ]
