# Generated by Django 3.0.5 on 2020-04-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0013_auto_20200417_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='is active'),
        ),
    ]
