# Generated by Django 3.0.5 on 2020-04-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0014_serviceorder_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='amount',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.CostCenter', verbose_name='cost center'),
        ),
    ]
