# Generated by Django 3.0.5 on 2020-04-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0015_auto_20200423_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='reference'),
        ),
    ]
