# Generated by Django 3.0.5 on 2020-05-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0016_serviceorder_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='estimated_closing_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='estimated closing date'),
        ),
    ]
