# Generated by Django 3.0.5 on 2020-09-17 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_transport_services', '0017_auto_20200513_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceChargeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=120, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'type of service charges',
                'verbose_name_plural': 'types of service charges',
            },
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user creatsettingsed'),
        ),
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('value1', models.CharField(blank=True, default='', max_length=120, verbose_name='value 1')),
                ('value2', models.CharField(blank=True, default='', max_length=120, verbose_name='value 2 ')),
                ('observation', models.TextField(blank=True, default='', verbose_name='observation')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.ServiceOrder', verbose_name='service order')),
                ('type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.ServiceChargeType', verbose_name='type')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user created')),
            ],
            options={
                'verbose_name': 'service charge',
                'verbose_name_plural': 'service charges',
            },
        ),
    ]
