# Generated by Django 3.0.5 on 2020-09-17 22:41

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0018_auto_20200917_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicechargetype',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='servicechargetype',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
    ]
