# Generated by Django 3.0.5 on 2020-09-17 22:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0021_remove_servicechargetype_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicechargetype',
            name='color',
            field=colorfield.fields.ColorField(default='#EEEEEE', max_length=18, verbose_name='color'),
        ),
    ]
