# Generated by Django 3.0.5 on 2020-09-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0022_servicechargetype_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecharge',
            name='value1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='value 1'),
        ),
        migrations.AlterField(
            model_name='servicecharge',
            name='value2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='value 2 '),
        ),
    ]
