# Generated by Django 3.0.5 on 2020-09-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0023_auto_20200917_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecharge',
            name='image',
            field=models.URLField(default='', verbose_name='image'),
        ),
    ]
