# Generated by Django 3.0.5 on 2020-09-18 03:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0009_auto_20200918_0226'),
        ('app_transport_services', '0024_servicecharge_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=80, unique=True, verbose_name='name')),
                ('code', models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'service order type',
                'verbose_name_plural': 'type of services',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='contract',
            name='min_number_services',
            field=models.IntegerField(blank=True, null=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='code',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='address_lat_long',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='address latitude and longitude'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='app_general.Subsidiary', verbose_name='destination'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='is_loaded',
            field=models.BooleanField(default=False, verbose_name='is loaded'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='app_general.Subsidiary', verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='volume'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(blank=True, max_length=80, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('code', models.CharField(blank=True, max_length=80, verbose_name='code')),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='kg', max_digits=12, null=True, verbose_name='max weight')),
                ('max_volume', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='m2', max_digits=12, null=True, verbose_name='max volume')),
                ('efficiency', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='lt', max_digits=12, null=True, verbose_name='max volume')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.Brand', verbose_name='brand')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.EquipmentType', verbose_name='type')),
            ],
            options={
                'verbose_name': 'model',
                'verbose_name_plural': 'model',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.Model', verbose_name='model'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.ServiceOrderType', verbose_name='type'),
        ),
    ]
