# Generated by Django 3.0.5 on 2020-09-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0025_auto_20200918_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='efficiency',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='lt', max_digits=12, null=True, verbose_name='efficiency'),
        ),
    ]
