# Generated by Django 3.0.5 on 2020-09-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0027_auto_20200918_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='efficiency',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='km * lt', max_digits=12, null=True, verbose_name='efficiency'),
        ),
        migrations.AlterField(
            model_name='model',
            name='max_volume',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, help_text='m3', max_digits=12, null=True, verbose_name='max volume'),
        ),
        migrations.AlterField(
            model_name='model',
            name='max_weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, help_text='kg', max_digits=12, null=True, verbose_name='max weight'),
        ),
    ]
