# Generated by Django 3.0.5 on 2020-09-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0028_auto_20200918_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='max_volume',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, help_text='m3', max_digits=12, null=True, verbose_name='max volume'),
        ),
        migrations.AlterField(
            model_name='model',
            name='max_weight',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, help_text='kg', max_digits=12, null=True, verbose_name='max weight'),
        ),
    ]
