# Generated by Django 3.0.5 on 2020-09-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0029_auto_20200918_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, help_text='m3', max_digits=12, null=True, verbose_name='volume'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, help_text='kg', max_digits=12, null=True, verbose_name='weight'),
        ),
    ]
