# Generated by Django 3.0.5 on 2020-09-18 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0030_auto_20200918_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceordertype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='serviceordertype',
            name='modified',
        ),
    ]
