# Generated by Django 3.0.5 on 2020-09-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0032_auto_20200918_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecharge',
            name='value1',
            field=models.DecimalField(blank=True, decimal_places=0, default=0.0, help_text='$ pesos', max_digits=12, null=True, verbose_name='value 1'),
        ),
    ]
