# Generated by Django 3.0.5 on 2020-09-23 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_transport_services', '0033_auto_20200918_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user created'),
        ),
    ]
