# Generated by Django 3.0.5 on 2020-09-23 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0034_auto_20200923_1035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceCharge',
        ),
        migrations.DeleteModel(
            name='ServiceChargeType',
        ),
    ]
