# Generated by Django 3.0.5 on 2020-09-23 22:52

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_transport_services', '0035_auto_20200923_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=120, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='name')),
                ('color', colorfield.fields.ColorField(default='#EEEEEE', max_length=18, verbose_name='color')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'cost type',
                'verbose_name_plural': 'cost types',
            },
        ),
        migrations.CreateModel(
            name='ServiceCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('value1', models.DecimalField(blank=True, decimal_places=0, default=0.0, help_text='$ pesos', max_digits=12, null=True, verbose_name='value 1')),
                ('value2', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='value 2 ')),
                ('image', models.URLField(blank=True, default='', null=True, verbose_name='image')),
                ('observation', models.TextField(blank=True, default='', verbose_name='observation')),
                ('cost_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.CostType', verbose_name='cost type')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.ServiceOrder', verbose_name='service order')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user created')),
            ],
            options={
                'verbose_name': 'service cost',
                'verbose_name_plural': 'service costs',
            },
        ),
    ]
