# Generated by Django 3.0.5 on 2020-09-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0036_costtype_servicecost'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecost',
            name='has_double_value',
            field=models.BooleanField(default=False, verbose_name='has double value'),
        ),
    ]
