# Generated by Django 3.0.5 on 2020-09-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0037_servicecost_has_double_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='min_number_services',
            field=models.IntegerField(blank=True, null=True, verbose_name='min number services'),
        ),
    ]
