# Generated by Django 3.0.5 on 2020-10-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0038_auto_20200924_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecost',
            name='has_double_value',
        ),
        migrations.AddField(
            model_name='costtype',
            name='has_double_value',
            field=models.BooleanField(default=False, verbose_name='has double value'),
        ),
    ]
