# Generated by Django 3.0.5 on 2020-10-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0039_auto_20201001_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='number_services_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='number services days'),
        ),
    ]
