# Generated by Django 3.0.5 on 2020-10-08 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0040_contract_number_services_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecost',
            name='cost_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.CostType', verbose_name='cost type'),
        ),
        migrations.AlterField(
            model_name='servicecost',
            name='service_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.ServiceOrder', verbose_name='service order'),
        ),
    ]
