# Generated by Django 3.0.5 on 2020-10-08 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0041_auto_20201008_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecost',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.Equipment', verbose_name='equipment'),
        ),
    ]
