# Generated by Django 3.0.5 on 2020-10-18 08:26

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0042_servicecost_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceordertype',
            name='color',
            field=colorfield.fields.ColorField(default='#EEEEEE', max_length=18, verbose_name='color'),
        ),
    ]
