# Generated by Django 3.0.5 on 2020-10-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0043_serviceordertype_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklogtype',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='code'),
        ),
    ]
