# Generated by Django 3.0.5 on 2021-07-30 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0044_worklogtype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.ServiceOrderType', verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_order_type', to='app_transport_services.ServiceOrderType', verbose_name='type'),
        ),
    ]
