# Generated by Django 3.2.5 on 2021-08-22 16:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0045_auto_20210730_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='longitude')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.serviceorder', verbose_name='service order')),
            ],
            options={
                'verbose_name': 'tracking',
                'verbose_name_plural': 'tracking',
            },
        ),
    ]
