# Generated by Django 3.2.5 on 2021-08-27 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0046_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='service_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.serviceorder', verbose_name='service order'),
        ),
    ]
