# Generated by Django 3.2.5 on 2021-08-27 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_transport_services', '0047_alter_tracking_service_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='latitude'),
        ),
    ]
