# Generated by Django 3.2.5 on 2021-08-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0048_auto_20210827_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='longitude'),
        ),
    ]
