# Generated by Django 3.2.5 on 2021-08-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0049_alter_tracking_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True, verbose_name='longitude'),
        ),
    ]
