# Generated by Django 3.2.5 on 2021-08-27 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0104_alter_process_module'),
        ('app_transport_services', '0050_auto_20210827_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.provider', verbose_name='provider'),
        ),
    ]
