# Generated by Django 3.2.5 on 2021-09-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0051_alter_serviceorder_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='estimated_closing_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='estimated closing date'),
        ),
    ]
