# Generated by Django 3.0.5 on 2021-05-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('discrepancy', 'discrepancy'), ('completed', 'completed')], default='pending', max_length=255, verbose_name='status'),
        ),
    ]
