# Generated by Django 3.0.5 on 2021-05-07 06:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0092_auto_20210507_0218'),
        ('app_purchase_order', '0002_purchaseorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('company', models.CharField(blank=True, max_length=250, null=True, verbose_name='company')),
                ('patent', models.CharField(blank=True, max_length=250, null=True, verbose_name='patent')),
                ('driver', models.CharField(blank=True, max_length=250, null=True, verbose_name='driver')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('discrepancy', 'discrepancy'), ('completed', 'completed')], default='pending', max_length=255, verbose_name='status')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='observation')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('organization', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.Organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'reception',
                'verbose_name_plural': 'receptions',
            },
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_purchase_order.PurchaseOrder', verbose_name='purchase_order'),
        ),
        migrations.CreateModel(
            name='ReceptionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='quantity')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('purchase_order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_purchase_order.PurchaseOrderDetail', verbose_name='purchase order detail')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_purchase_order.Reception', verbose_name='reception')),
            ],
            options={
                'verbose_name': 'reception detail',
                'verbose_name_plural': 'reception details',
            },
        ),
    ]
