# Generated by Django 3.0.5 on 2021-05-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase_order', '0003_auto_20210507_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='receptiondetail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
