# Generated by Django 3.0.5 on 2021-05-07 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_general', '0093_auto_20210507_0248'),
        ('app_purchase_order', '0004_auto_20210507_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFileOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('file', models.FileField(default='', upload_to='images/%Y/%m/orig', verbose_name='file')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('uploaded', models.BooleanField(default=False, verbose_name='uploaded')),
                ('organization', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.Organization', verbose_name='organization')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user created')),
            ],
            options={
                'verbose_name': 'import file',
                'verbose_name_plural': 'import files',
            },
        ),
    ]
