# Generated by Django 3.0.5 on 2021-05-07 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase_order', '0005_importfileorderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfileorderdetail',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_purchase_order.PurchaseOrder', verbose_name='purchase_order'),
        ),
    ]
