# Generated by Django 3.0.5 on 2021-05-07 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase_order', '0006_importfileorderdetail_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfileorderdetail',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_purchase_order.PurchaseOrder', verbose_name='purchase order'),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_purchase_order.PurchaseOrder', verbose_name='purchase order'),
        ),
    ]
