# Generated by Django 3.0.5 on 2021-01-04 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_general', '0016_auto_20201028_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='code')),
                ('description', models.CharField(max_length=255, unique=True, verbose_name='description')),
                ('type_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='app_component.Type', verbose_name='type parent')),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='code')),
                ('description', models.CharField(max_length=255, unique=True, verbose_name='description')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='longitude')),
                ('subsidiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.Subsidiary', verbose_name='subsidiary')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('code_1', models.CharField(blank=True, default='', max_length=100, verbose_name='code 1')),
                ('code_2', models.CharField(blank=True, default='', max_length=100, verbose_name='code 2')),
                ('qr_code', models.CharField(blank=True, default='', max_length=100, verbose_name='qr code')),
                ('quantity', models.IntegerField(blank=True, default=0, verbose_name='quantity')),
                ('address_lat_long', models.CharField(blank=True, default='', max_length=100, verbose_name='address latitude and longitude')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('observation', models.TextField(blank=True, default='', verbose_name='observation')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, default=0.0, help_text='kg', max_digits=12, null=True, verbose_name='weight')),
                ('volume', models.DecimalField(blank=True, decimal_places=1, default=0.0, help_text='m3', max_digits=12, null=True, verbose_name='volume')),
                ('width', models.DecimalField(blank=True, decimal_places=1, default=0.0, help_text='mt', max_digits=12, null=True, verbose_name='width')),
                ('height', models.DecimalField(blank=True, decimal_places=1, default=0.0, help_text='mt', max_digits=12, null=True, verbose_name='height')),
                ('priority', models.BooleanField(blank=True, default=False, verbose_name='priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_component.Location', verbose_name='location')),
                ('subsidiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.Subsidiary', verbose_name='subsidiary')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='app_component.Type', verbose_name='type')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user created')),
            ],
            options={
                'verbose_name': 'component',
                'verbose_name_plural': 'components',
            },
        ),
    ]
