# Generated by Django 3.0.5 on 2021-01-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
    ]
