# Generated by Django 3.0.5 on 2021-01-08 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0003_auto_20210108_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('value', models.URLField(blank=True, null=True, verbose_name='value')),
                ('code', models.CharField(blank=True, default='image', max_length=100, verbose_name='code')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_component.Component', verbose_name='component')),
            ],
            options={
                'verbose_name': 'attached file',
                'verbose_name_plural': 'attached file',
            },
        ),
    ]
