# Generated by Django 3.0.5 on 2021-01-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0004_attachedfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedfiles',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
