# Generated by Django 3.0.5 on 2021-01-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0005_attachedfiles_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, help_text='mt', max_digits=12, null=True, verbose_name='long'),
        ),
    ]
