# Generated by Django 3.0.5 on 2021-01-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0006_component_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='address_lat_long',
        ),
        migrations.AddField(
            model_name='component',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='component',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='longitude'),
        ),
    ]
