# Generated by Django 3.0.5 on 2021-01-18 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0007_auto_20210110_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedfiles',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, default='image', max_length=100, verbose_name='code')),
                ('value_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='value 1')),
                ('value_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='value 2')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('observation', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('priority', models.BooleanField(default=False, null=True, verbose_name='priority')),
                ('order', models.IntegerField(default=0, null=True, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_component.Component', verbose_name='component')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_component.Type', verbose_name='state')),
            ],
            options={
                'verbose_name': 'workflow',
                'verbose_name_plural': 'workflows',
                'unique_together': {('code', 'component')},
            },
        ),
    ]
