# Generated by Django 3.0.5 on 2021-01-18 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0008_auto_20210118_0455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'verbose_name': 'work flow', 'verbose_name_plural': 'workflows'},
        ),
    ]
