# Generated by Django 3.0.5 on 2021-01-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0009_auto_20210118_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='observation',
            field=models.TextField(blank=True, default='', null=True, verbose_name='observation'),
        ),
    ]
