# Generated by Django 3.0.5 on 2021-01-18 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0020_auto_20210118_0635'),
        ('app_component', '0010_auto_20210118_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.Process', verbose_name='process'),
        ),
    ]
