# Generated by Django 3.0.5 on 2021-01-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0011_workflow_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='order',
        ),
    ]
