# Generated by Django 3.0.5 on 2021-01-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0013_auto_20210118_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
