# Generated by Django 3.0.5 on 2021-01-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0014_auto_20210118_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='processed'),
        ),
    ]
