# Generated by Django 3.0.5 on 2021-01-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0015_workflow_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='priority',
            field=models.BooleanField(default=False, verbose_name='priority'),
        ),
    ]
