# Generated by Django 3.0.5 on 2021-01-18 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_component', '0016_auto_20210118_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='modifying_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='modifying user'),
        ),
    ]
