# Generated by Django 3.0.5 on 2021-01-18 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_component', '0018_auto_20210118_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='user_created',
        ),
        migrations.AddField(
            model_name='component',
            name='creator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_user', to=settings.AUTH_USER_MODEL, verbose_name='creator user'),
        ),
        migrations.AddField(
            model_name='component',
            name='editor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_user', to=settings.AUTH_USER_MODEL, verbose_name='editor user'),
        ),
    ]
