# Generated by Django 3.0.5 on 2021-01-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0019_auto_20210118_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
    ]
