# Generated by Django 3.0.5 on 2021-01-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0021_auto_20210121_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='code'),
        ),
    ]
