# Generated by Django 3.0.5 on 2021-01-23 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_general', '0041_auto_20210121_0949'),
        ('app_component', '0022_auto_20210123_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFlowLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='code')),
                ('value_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='value 1')),
                ('value_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='value 2')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('observation', models.TextField(blank=True, default='', null=True, verbose_name='observation')),
                ('priority', models.BooleanField(default=False, verbose_name='priority')),
                ('processed', models.BooleanField(default=False, verbose_name='processed')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_component.Component', verbose_name='component')),
                ('editor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='editor user')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.Process', verbose_name='process')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_component.Type', verbose_name='state')),
            ],
            options={
                'verbose_name': 'workflows log',
                'verbose_name_plural': 'workflow logs',
            },
        ),
    ]
