# Generated by Django 3.0.5 on 2021-02-25 20:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0023_workflowlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('observation', models.TextField(blank=True, default='', null=True, verbose_name='observation')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_component.Component', verbose_name='component')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_component.Location', verbose_name='location')),
            ],
            options={
                'verbose_name': 'components location',
                'verbose_name_plural': 'component locations',
            },
        ),
    ]
