# Generated by Django 3.0.5 on 2021-02-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0024_componentlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='componentlocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='longitude'),
        ),
    ]
