# Generated by Django 3.0.5 on 2021-02-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0025_auto_20210225_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentlocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='componentlocation',
            name='longitude',
        ),
    ]
