# Generated by Django 3.0.5 on 2021-03-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0026_auto_20210226_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='published',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
        migrations.AddField(
            model_name='component',
            name='published_url',
            field=models.URLField(blank=True, default='', verbose_name='published url'),
        ),
    ]
