# Generated by Django 3.0.5 on 2021-03-09 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0027_auto_20210301_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='value_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='value 3'),
        ),
        migrations.CreateModel(
            name='MetaWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='key')),
                ('code', models.CharField(max_length=100, verbose_name='code')),
                ('value', models.TextField(blank=True, null=True, verbose_name='value')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_component.WorkFlow', verbose_name='workflow')),
            ],
            options={
                'verbose_name': 'meta',
                'verbose_name_plural': 'meta',
            },
        ),
    ]
