# Generated by Django 3.0.5 on 2021-03-09 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0028_auto_20210309_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='upload',
            field=models.BooleanField(default=False, verbose_name='upload'),
        ),
        migrations.AlterField(
            model_name='metaworkflow',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_component.WorkFlow', verbose_name='workflow'),
        ),
    ]
