# Generated by Django 3.0.5 on 2021-03-14 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0031_auto_20210314_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaworkflow',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_component.WorkFlow', verbose_name='workflow'),
        ),
    ]
