# Generated by Django 3.0.5 on 2021-03-15 07:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_services', '0044_worklogtype_code'),
        ('app_component', '0052_auto_20210314_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaworkflow',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_component.WorkFlow', verbose_name='workflow'),
        ),
        migrations.CreateModel(
            name='ComponentServiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_component.Component', verbose_name='component')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_transport_services.ServiceOrder', verbose_name='service order')),
            ],
            options={
                'verbose_name': 'components by service orders',
                'verbose_name_plural': 'components by service orders',
            },
        ),
    ]
