# Generated by Django 3.0.5 on 2021-03-15 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0059_auto_20210315_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentserviceorder',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='metaworkflow',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_component.WorkFlow', verbose_name='workflow'),
        ),
    ]
