# Generated by Django 3.0.5 on 2021-03-15 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_component', '0060_auto_20210315_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentserviceorder',
            name='editor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='editor user'),
        ),
        migrations.AlterField(
            model_name='metaworkflow',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_component.WorkFlow', verbose_name='workflow'),
        ),
    ]
