# Generated by Django 3.0.5 on 2021-04-15 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0078_auto_20210330_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='ticket',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='ticket'),
        ),
        migrations.AlterField(
            model_name='metaworkflow',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_component.WorkFlow', verbose_name='workflow'),
        ),
    ]
