# Generated by Django 3.0.5 on 2021-04-15 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0080_auto_20210415_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='create_type',
            field=models.CharField(blank=True, choices=[('subsidiary', 'subsidiary'), ('mel', 'mel')], default='subsidiary', max_length=100, verbose_name='create type'),
        ),
        migrations.AlterField(
            model_name='metaworkflow',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_component.WorkFlow', verbose_name='workflow'),
        ),
    ]
