# Generated by Django 3.0.5 on 2021-04-29 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0091_auto_20210428_1238'),
        ('app_component', '0085_auto_20210428_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='subsidiary2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidiary2', to='app_general.Subsidiary', verbose_name='subsidiary2'),
        ),
        migrations.AlterField(
            model_name='metaworkflow',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_component.WorkFlow', verbose_name='workflow'),
        ),
    ]
