# Generated by Django 3.0.5 on 2021-05-07 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0095_auto_20210507_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='processed'),
        ),
        migrations.AlterField(
            model_name='metaworkflow',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_component.WorkFlow', verbose_name='workflow'),
        ),
    ]
