# Generated by Django 3.0.5 on 2021-06-24 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0095_auto_20210507_0822'),
        ('app_component', '0096_auto_20210507_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(default='', max_length=80, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='metaworkflow',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_component.WorkFlow', verbose_name='workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'code', 'subsidiary')},
        ),
    ]
