# Generated by Django 3.0.5 on 2021-07-01 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_component', '0097_auto_20210624_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='new_contract',
            field=models.BooleanField(default=False, verbose_name='new contract'),
        ),
        migrations.AlterField(
            model_name='metaworkflow',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_component.WorkFlow', verbose_name='workflow'),
        ),
    ]
